### ISSUE TITLE
logstash 5.2.0 support

### ISSUE THREAD

**Issue by alancnet** [logstash-plugins/logstash-input-websocket#15] opened 2017-02-13 22:28 UTC
No text

**Comment by magnusbaeck** [comment] 2017-02-14 06:59
@alancnet, could you please elaborate? As of #14 (included in v4.0.0) the plugin is 5.x compatible and I'm not aware of any problems with Logstash 5.2.

**Comment by pvdvreede** [comment] 2017-02-27 06:14
I have had an issue with gem version incompatibilities. ftw is using addressable 2.2 but logstash somewhere requires 2.3.8.

I have done a PR to ftw to try and fix this (see https://github.com/jordansissel/ruby-ftw/pull/36), but I am not sure if something can be done here to get around this issue?

**Comment by magnusbaeck** [comment] 2017-06-07 18:48
So the problem is that the ftw library needed by this plugin requires 2.2.x of the addressable library, but other Logstash plugins require 2.3.x. The PR filed by @pvdvreede (jordansissel/ruby-ftw#36) attempts to address this, and when merged and included in a new ftw release we can bump the required version of ftw and release a new logstash-input-websocket.

**Comment by moshe-sa** [comment] 2017-06-12 14:53
Any update?

**Comment by magnusbaeck** [comment] 2017-06-12 15:13
@moshe-sa, as indicated in my comment a few days ago this issue won't move until the referenced ruby-ftw PR is resolved.

**Comment by magnusbaeck** [comment] 2019-03-03 20:11
The PR quoted above is still unmerged but an equivalent PR, https://github.com/jordansissel/ruby-ftw/pull/38, has been merged and I've been able to install this plugin in various Logstash releases, including the currently latest one (6.6.1).

I'm therefore closing this issue since the specific points raised have been addressed, but do note issue #19 which describes the exact same class of problem but for Logstash 7.0, currently in beta.

**Closed by magnusbaeck** 2019-03-03 20:11 UTC
Labels: breaking-compatibility
